version: '3'
services:
  elastic_express:
    image: elasticsearch:7.7.1
    container_name: elasticsearch_expressjs
    environment:
      - node.name=elastic_express
      - cluster.name=es-express
      - cluster.initial_master_nodes=elastic_express
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - "./test:/__test__"
    command: sh -c "node data.js & wait-for-it.sh localhost:9200 -- npm run test"
    ports:
      - 9200:9200
    networks:
      - elastic

volumes:
  data02:
    driver: local

networks:
  elastic:
    driver: bridge